[2024-11-02T06:30:51.990+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-11-02T06:30:52.014+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-17T00:00:00+00:00 [queued]>
[2024-11-02T06:30:52.016+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T06:30:52.069+0000] {taskinstance.py:1380} INFO - Executing <Task(KafkaProducerOperator): generate_txn_fact_data> on 2024-08-17 00:00:00+00:00
[2024-11-02T06:30:52.077+0000] {standard_task_runner.py:57} INFO - Started process 4276 to run task
[2024-11-02T06:30:52.085+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transaction_facts_generator', 'generate_txn_fact_data', 'scheduled__2024-08-17T00:00:00+00:00', '--job-id', '1117', '--raw', '--subdir', 'DAGS_FOLDER/transaction_facts_generator.py', '--cfg-path', '/tmp/tmpvc9g45ko']
[2024-11-02T06:30:52.090+0000] {standard_task_runner.py:85} INFO - Job 1117: Subtask generate_txn_fact_data
[2024-11-02T06:30:52.198+0000] {task_command.py:415} INFO - Running <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-08-17T00:00:00+00:00 [running]> on host 5e812a6a7c02
[2024-11-02T06:30:52.364+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhtranquang' AIRFLOW_CTX_DAG_ID='transaction_facts_generator' AIRFLOW_CTX_TASK_ID='generate_txn_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-17T00:00:00+00:00'
[2024-11-02T06:30:52.371+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: connecting to kafka_broker:9092 [('172.20.0.4', 9092) IPv4]
[2024-11-02T06:30:52.374+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-11-02T06:30:52.379+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: Connection complete.
[2024-11-02T06:30:52.486+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-11-02T06:30:52.487+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-11-02T06:30:52.494+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/kafka_operator.py", line 58, in execute
    transaction = self.generate_transaction_data(row_num)
  File "/opt/airflow/plugins/kafka_operator.py", line 31, in generate_transaction_data
    transaction_type = random.choice(transaction_types)
AttributeError: module 'random' has no attribute 'choic'
[2024-11-02T06:30:52.523+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20240817T000000, start_date=20241102T063051, end_date=20241102T063052
[2024-11-02T06:30:52.566+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1117 for task generate_txn_fact_data (module 'random' has no attribute 'choic'; 4276)
[2024-11-02T06:30:52.623+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-02T06:30:52.683+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
