[2024-11-02T06:31:34.189+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-11-02T06:31:34.208+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-18T00:00:00+00:00 [queued]>
[2024-11-02T06:31:34.209+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T06:31:34.246+0000] {taskinstance.py:1380} INFO - Executing <Task(KafkaProducerOperator): generate_txn_fact_data> on 2024-10-18 00:00:00+00:00
[2024-11-02T06:31:34.257+0000] {standard_task_runner.py:57} INFO - Started process 4505 to run task
[2024-11-02T06:31:34.263+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transaction_facts_generator', 'generate_txn_fact_data', 'scheduled__2024-10-18T00:00:00+00:00', '--job-id', '1179', '--raw', '--subdir', 'DAGS_FOLDER/transaction_facts_generator.py', '--cfg-path', '/tmp/tmp_5vn05et']
[2024-11-02T06:31:34.269+0000] {standard_task_runner.py:85} INFO - Job 1179: Subtask generate_txn_fact_data
[2024-11-02T06:31:34.361+0000] {task_command.py:415} INFO - Running <TaskInstance: transaction_facts_generator.generate_txn_fact_data scheduled__2024-10-18T00:00:00+00:00 [running]> on host 5e812a6a7c02
[2024-11-02T06:31:34.499+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhtranquang' AIRFLOW_CTX_DAG_ID='transaction_facts_generator' AIRFLOW_CTX_TASK_ID='generate_txn_fact_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-18T00:00:00+00:00'
[2024-11-02T06:31:34.507+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: connecting to kafka_broker:9092 [('172.20.0.4', 9092) IPv4]
[2024-11-02T06:31:34.510+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-11-02T06:31:34.513+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka_broker:9092 <connecting> [IPv4 ('172.20.0.4', 9092)]>: Connection complete.
[2024-11-02T06:31:34.617+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2024-11-02T06:31:34.617+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2024-11-02T06:31:34.621+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/kafka_operator.py", line 58, in execute
    transaction = self.generate_transaction_data(row_num)
  File "/opt/airflow/plugins/kafka_operator.py", line 31, in generate_transaction_data
    transaction_type = random.choice(transaction_types)
AttributeError: module 'random' has no attribute 'choic'
[2024-11-02T06:31:34.635+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transaction_facts_generator, task_id=generate_txn_fact_data, execution_date=20241018T000000, start_date=20241102T063134, end_date=20241102T063134
[2024-11-02T06:31:34.729+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1179 for task generate_txn_fact_data (module 'random' has no attribute 'choic'; 4505)
[2024-11-02T06:31:34.759+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-02T06:31:34.820+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
