[2024-11-02T14:53:37.804+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2024-11-02T14:53:37.816+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2024-11-01T00:00:00+00:00 [queued]>
[2024-11-02T14:53:37.817+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-11-02T14:53:37.842+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_account_dim> on 2024-11-01 00:00:00+00:00
[2024-11-02T14:53:37.850+0000] {standard_task_runner.py:57} INFO - Started process 4960 to run task
[2024-11-02T14:53:37.858+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_account_dim', 'scheduled__2024-11-01T00:00:00+00:00', '--job-id', '1807', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpmapx_hym']
[2024-11-02T14:53:37.864+0000] {standard_task_runner.py:85} INFO - Job 1807: Subtask ingest_account_dim
[2024-11-02T14:53:37.953+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2024-11-01T00:00:00+00:00 [running]> on host 5e812a6a7c02
[2024-11-02T14:53:38.085+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='minhtranquang' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_account_dim' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T00:00:00+00:00'
[2024-11-02T14:53:38.089+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T14:53:38.091+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/account_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=account_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimeter%22%3A%22%2C%22%7D"']
[2024-11-02T14:53:38.105+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T14:53:38.119+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-11-02T14:53:38.120+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-11-02T14:53:38.175+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  3606  100   702  100  2904  12535  51857 --:--:-- --:--:-- --:--:-- 65563
[2024-11-02T14:53:38.177+0000] {subprocess.py:93} INFO - {"code":500,"error":"Caught exception when ingesting file into table: account_dim_OFFLINE. Unrecognized field \"delimeter\" (class org.apache.pinot.plugin.inputformat.csv.CSVRecordReaderConfig), not marked as ignorable (15 known properties: \"ignoreEmptyLines\", \"delimiter\", \"escapeCharacter\", \"skipUnParseableLines\", \"skipHeader\", \"quoteCharacter\", \"multiValueDelimiter\", \"multiValueDelimiterEnabled\", \"fileFormat\", \"recordSeparator\", \"commentMarker\", \"ignoreSurroundingSpaces\", \"header\", \"nullStringValue\", \"quoteMode\"])\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.apache.pinot.plugin.inputformat.csv.CSVRecordReaderConfig[\"delimeter\"])"}
[2024-11-02T14:53:38.177+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-02T14:53:38.228+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dimension_batch_ingestion, task_id=ingest_account_dim, execution_date=20241101T000000, start_date=20241102T145337, end_date=20241102T145338
[2024-11-02T14:53:38.271+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-02T14:53:38.307+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
